//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banh()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
        }
    
        public int MaBanh { get; set; }
        public string TenBanh { get; set; }
        public Nullable<bool> TrangThaiBanh { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> LoaiBanh { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<bool> TrangThaiXoa { get; set; }
        public string TenLoaiBanh { get; set; }
        public string TenTrangThaiBanh { get; set; }
    
        public virtual LoaiBanh LoaiBanh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
    }
}
