//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHD
    {
        public int MaCTHoaDon { get; set; }
        public Nullable<int> MaBanh { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual Banh Banh { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
