//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public int Id { get; set; }
        public int MaBanh { get; set; }
        public string TenHinh { get; set; }
    
        public virtual Banh Banh { get; set; }
    }
}
