//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public string IdTaiKhoan { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string MaKhach { get; set; }
        public Nullable<int> TongTien { get; set; }
    }
}
